### ISSUE TITLE
Add SmaCC_Source_Editing in a group

### ISSUE THREAD

**Issue by badetitou** [j-brant/SmaCC#11]
Hello, 

I'd like to use SmaCC for Java and with the source code. But, SmaCC_Source_Editing package is not present in any group (except "all").

Is it possible to have it alone in a group so I can configure my baseline to use both Java and SmaCC_Source_Editing?

(I can do a PR if you want)

Thanks!

**Comment by j-brant** [comment]
Please submit a PR.
