### ISSUE TITLE
Debugging in Pharo 10/11 

### ISSUE THREAD

**Issue by sbragagnolo** [j-brant/SmaCC#21]
I was about to get my hands on migrating the debugger to Pharo 10. 
I happily discovered that you already did it! 
Still, I wondered about the code to check if everything was working fine, and I learned that the parsing debugger does not work with non-GLR parsers. 
As a workaround, I implement two methods at #SmaCCParser 
 #SmaCCParser>>states 
     ^ stateStack.

 #SmaCCParser>>currentState 
     ^ currentToken.

It seems to be enough. If you are interested, I can make a pull request with that. I would like any what you think about these changes.

**Comment by j-brant** [comment]
Thanks for the report. I changed the code so that it shouldn't try to update the glr label when we don't have a glr parser.
