### ISSUE TITLE
Cannot save new parser in Pharo12

### ISSUE THREAD

**Issue by badetitou** [j-brant/SmaCC#23]
Hello

Since Pharo 12 the class builder has changed. 
I tried to create a new SmaCC parser for Mermaid grammar. But cannot save the parser because of a bug when saving. It uses the old class builder method. 

I can try to fix the issue. Would you accept a PR to make it available for Pharo12 (I hope with retro compatibility for the older Pharo version ) ?

**Comment by badetitou** [comment]
I have started a branch here if you are interested
https://github.com/badetitou/SmaCC/tree/23-Cannot-save-new-parser-in-Pharo12

For now, I still have a little issue with traits Composition. 
(I also commited the automatic deprecation. I hope it can not create future issue)

**Comment by j-brant** [comment]
I added some changes to get it to compile with an AST.

**Comment by badetitou** [comment]
Super great! Thanks a lot @j-brant
