### ISSUE TITLE
SmaCC_Elixir Missing identifiers

### ISSUE THREAD

**Issue by mariari** [j-brant/SmaCC#33]
The Elixir source isn't great at explaining what all the identifiers are in the source. Thus a lot of them go undefined.

The code to properly understand it can be seen here:

https://github.com/elixir-lang/elixir/blob/f38895cebba0fa06f686e1dd9b74e5729aebcb45/lib/elixir/src/elixir_tokenizer.erl

What is missing are:

1. <op_identifier>
2. <bracket_identifier>
3. <paren_identifier>
4. <do_identifier>
5. <dot_call_op>

in #28 I define `dot_call_op` properly However I fail to properly address 1-4.

2-3 are easy enough as they just need to either peek ahead, or reset the stream to being 1 character back while dropping their parsed `(` or `[`.

4-5 I'm unsure how to handle.

**Comment by j-brant** [comment]
If you look at `ElixirParser>>#actionsForCurrentToken`, you can see that they are defined.

**Comment by mariari** [comment]
> If you look at `ElixirParser>>#actionsForCurrentToken`, you can see that they are defined.

Thanks I somehow missed that when looking over things.

Are there good ways for testing when rules for this go off? I may have found an issue with it.

**Comment by mariari** [comment]
A good explanation can be seen here:

https://github.com/j-brant/SmaCC/pull/37#issuecomment-2474261442
